Add recommended Ethernet adapter
Signed-off-by: Devnol <pgkoutsoumanis@gmail.com>
RiiConnect24/Wii-Guide pull request #233
Opened 2021-11-10 15:33 UTC by Devnol

2021-11-10 16:54 UTC, KcrPL requested changes
Hmm... I don't think we should put links to Amazon etc. on wii.guide.

2021-11-10 16:57 UTC, Devnol commented
This edit was requested by the Wii mini community as a lot of people have been asking for an Ethernet adapter compatible with the console that is still actively being sold. The links as you can see are non-affiliate but honestly it's up to you.

2021-11-10 16:59 UTC, KcrPL commented
Actually that would be really useful now that I think about it. Let's wait for feedback from someone else.

2021-11-10 18:34 UTC, Peter0x44 commented
I don't like the link either, but a large part is wording... I don't think there are much better alternatives
How about "this ethernet adapter has been tested and is known to work" or so, I don't like "we recommend"

2021-11-10 18:38 UTC, Devnol commented
Fair enough,

2021-11-10 18:38 UTC, Artuto commented
~~Let's put an affiliate link 🤑🥴~~

2021-11-10 18:39 UTC, Devnol commented
I don't see any reason not to honestly

2021-11-17 21:45 UTC, larsenv commented
I saw this earlier but didn't respond.

@KcrPL @Peter0x44 You're not really providing much of a reason why you're opposed to linking to Amazon. I personally think it's perfectly fine, no one will care as everyone knows about Amazon.

I say merge it, and perhaps we could also put some other Amazon links when we find something necessary (e.g. linking to a Wii Speak, recommended SD Card, USB drive, etc.)

2021-11-17 21:46 UTC, larsenv requested changes
"If you're planning to buy an adapter, first search with your favorite search engine or look at the product page and confirm if it uses this specific chip. This adapter from UGreen has been tested by many community members and is known to work:" is too wordy.

Simply say that the UGREEN adapter is recommended.

2021-11-17 21:48 UTC, Devnol commented
Yeah I guess it is a little to verbose but the part where we mention what chip the adapter needs to have is sort of crucial. I will trim the period tomorrow. Thanks for the feedback guys and have a good day.

2021-11-18 00:11 UTC, Peter0x44 commented
> You're not really providing much of a reason why you're opposed to linking to Amazon
I never really said I was opposed
> Simply say that the UGREEN adapter is recommended.
I don't think we should say explicitly "recommended" as that puts some burden of responsibility on us that it will actually work, which we can't guarantee

2021-11-23 14:14 UTC, Devnol commented
TBH I totally forgot about this, sorry for being late but here you go, the changes you requested.

2021-11-23 15:21 UTC, Peter0x44 commented
Much better, I think it's good now

2021-11-23 15:25 UTC, Peter0x44 approved these changes

2021-11-27 19:16 UTC, Rexogamer commented on _pages/en_US/cios-mini.md
> +The Wii and Wii mini consoles are only known to work with Ethernet adapters using the AX88772 chip. Please check that the product is compatible before you buy. This one from UGREEN is known to be com
minor capitalisation nitpick:
```suggestion
The Wii and Wii mini consoles are only known to work with Ethernet adapters using the AX88772 chip. Please check that the product is compatible before you buy. This one from UGREEN is known to be compatible: [Amazon Europe](https://www.amazon.de/dp/B00MYT481C), [Amazon US](https://www.amazon.com/dp/B08DRKYKMM/)
```

2021-11-27 19:17 UTC, Devnol commented on _pages/en_US/cios-mini.md
> +The Wii and Wii mini consoles are only known to work with Ethernet adapters using the AX88772 chip. Please check that the product is compatible before you buy. This one from UGREEN is known to be com
<img width="129" alt="image" src="https://user-images.githubusercontent.com/58105634/143719456-dd836d67-8f1b-49e7-a6e7-f0bc326b0315.png">
amazon is marketed lowercase

2021-11-27 19:18 UTC, Devnol commented on _pages/en_US/cios-mini.md
> +The Wii and Wii mini consoles are only known to work with Ethernet adapters using the AX88772 chip. Please check that the product is compatible before you buy. This one from UGREEN is known to be com
elsewhere it's Amazon but whatever I guess I can merge it

2021-11-27 19:22 UTC, Rexogamer approved these changes

2021-12-28 00:17 UTC, Peter0x44 commented
No one else has voiced any objections over how this is worded, and there has been more than enough time, so I'm going to merge it.

2021-12-28 00:17 UTC, merged