Update bluebomb.md
RiiConnect24/Wii-Guide pull request #283
Opened 2022-08-28 18:44 UTC by Snare-Hawk

add notice about chromebooks

2022-08-28 19:35 UTC, osfanbuff63 requested changes

2022-08-28 19:35 UTC, osfanbuff63 commented on _pages/en_US/bluebomb.md
> +  - A Chromebook running Lunix mode will not work as it does not have access to the hardware required to perform BlueBomb.
```suggestion
  - A Chromebook running Linux mode will not work as it does not have access to the hardware required to perform BlueBomb.
```

2022-08-29 21:15 UTC, osfanbuff63 approved these changes

2022-09-05 19:45 UTC, NightScript370 commented
Your addition sounds familiar to the sentence already declared above to denounce any WSFL support. Why not merge the two, or put the two next to eachother so that the reader's mind isn't reverted back to "oh, what *can't* I use this on"?
> Windows Subsystem for Linux will *not work* as it does not have direct access to the Bluetooth adapter or USB ports.

2023-01-09 18:24 UTC, Snare-Hawk commented
> Your addition sounds familiar to the sentence already declared above to denounce any WSFL support. Why not merge the two, or put the two next to eachother so that the reader's mind isn't reverted back to "oh, what _can't_ I use this on"?
> 
> > Windows Subsystem for Linux will _not work_ as it does not have direct access to the Bluetooth adapter or USB ports.

true

2023-01-09 19:08 UTC, Peter0x44 commented on _pages/en_US/bluebomb.md
> +  - Windows Subsystem for Linux nor a Chromebook running Linux mode will *not work* as it does not have direct access to the Bluetooth adapter or USB ports.
```suggestion
  - Windows Subsystem for Linux or a Chromebook running Linux mode will *not work* as it does not have direct access to the Bluetooth adapter or USB ports.
```
small nit, otherwise LGTM

2023-01-09 19:09 UTC, merged