add-modmii-page
RiiConnect24/Wii-Guide pull request #380
Opened 2023-08-11 05:52 UTC by playerjmr

2023-08-11 05:56 UTC, playerjmr commented
im not sure why but it didnt add the image or site navigation commits

2023-08-12 00:58 UTC, Naim2000 requested changes

2023-08-12 00:58 UTC, Naim2000 commented on _pages/en_US/modmii.md
> +      files to its temp folder for future use you can delete 'COPY_TO_SD'          | This option will download all of the required titles need for the Wii system menu (titles are downloaded from NUS)
```suggestion
| L = Load Download Queue          | This option will download all of the required titles need for the Wii system menu (titles are downloaded from NUS)                                                                                                                         |
```
Yeah the newlines here are straight up breaking the whole table

2023-08-12 00:58 UTC, Naim2000 commented on _pages/en_US/modmii.md
> +  IOS slots to prevent bricks from users manually up\downgrading Wii's      | Enables Modmiis Extra Brick Protection IOSes to be recommended and used in the syscheck updater tool.            |
```suggestion
| E = Extra Brick Protection in ModMii Wizard Guides  | Enables Modmiis Extra Brick Protection IOSes to be recommended and used in the syscheck updater tool.            |
```
(2)

2023-08-12 00:58 UTC, Naim2000 commented on _pages/en_US/modmii.md
> +  * PC programs saved portably if not running ModMii from C:                | Changes the save location for the downloadable PC programs.                                                      |
```suggestion
| PC = PC Programs Save Location                | Changes the save location for the downloadable PC programs.                                                      |
```
(3)

2023-08-12 00:58 UTC, Naim2000 commented on _pages/en_US/modmii.md
> +  * Useful for Wii Apps that require IOSs\MIOSs saved to Root               | Saves IOSs\MIOSs to Root instead of WAD Folder.                                                                  |
```suggestion
| RS = Root Save: Save IOSs\MIOSs to Root instead of WAD Folder               | Saves IOSs\MIOSs to Root instead of WAD Folder.                                                                  |
```
(4)

2023-08-12 00:58 UTC, Naim2000 commented on _pages/en_US/modmii.md
> +  * Folder sometimes required for offline usage of a few Wii Apps           | Deletes the folder used for compiling the wad file and just gives you the wad file.                              |
```suggestion
| 1 = Do not Keep 00000001 or NUS Folders for IOSs\MIOSs\SMs etc           | Deletes the folder used for compiling the wad file and just gives you the wad file.                              |
```
(5)

2023-08-12 01:46 UTC, playerjmr commented
thanks, i also want to add the png from the [modmii website](https://modmii.github.io/) and i think i typed the path wrong. its supposed to be /images/modmii.png

2023-08-12 01:56 UTC, Naim2000 commented
I mean i like it when images for a page are in their own folders anyway

2023-08-12 02:02 UTC, Naim2000 commented on _pages/en_US/modmii.md
> +{: .notice--info}
```suggestion
This Program does NOT come with a warranty, so you are responsible for any potential damage done to your Wii.
{: .notice--warning}

This program is NOT intended to be used for the vWii or the Wii Mini. Some tools may or may not work for these platforms.
{: .notice--warning}

```
Could use a bit more ⚠️ honestly. I could make all these changes myself but it kinda feels like i would just take away everything lol

2023-08-12 02:05 UTC, Naim2000 requested changes
Uhh i think i need to go resolve that previous review lol

2023-08-12 02:05 UTC, Naim2000 commented on _pages/en_US/modmii.md
> + Modmii is a PC program for windows created by XFlak that has various helpful tools for modding, including some tutorials that may not be currently available here on the wii.guide website. You can ch
Also this should probably switch spots with the "quick start guide" part

2023-08-12 06:10 UTC, playerjmr commented on _pages/en_US/modmii.md
> +{: .notice--info}
Feel free to make whatever changes that seem nessecary. I want this to look good just as you do. Personally I thought it was fine, except I forgot that {: .notice-warning} even existed.

2023-08-12 06:17 UTC, playerjmr commented on _pages/en_US/modmii.md
> + Modmii is a PC program for windows created by XFlak that has various helpful tools for modding, including some tutorials that may not be currently available here on the wii.guide website. You can ch
I was using the usbloader gx page as an example template, and it has the quick start guide message combined with a brief description of the program before listing the materials. I thought it would look nicer if I had seperated the quick start guide and the longer description.

2023-08-14 00:43 UTC, playerjmr commented on _pages/en_US/modmii.md
> + Modmii is a PC program for windows created by XFlak that has various helpful tools for modding, including some tutorials that may not be currently available here on the wii.guide website. You can ch
```suggestion
 This is a quick start guide on how to use Modmii on your Windows PC.

```

2023-08-14 00:44 UTC, playerjmr commented on _pages/en_US/modmii.md
> +This is a quick start guide on how to use Modmii on your Windows PC.
Modmii is a PC program for windows created by XFlak that has various helpful tools for modding, including some tutorials that may not be currently available here on the wii.guide website. You can choose to launch in Modmii skin, which has a more user friendly approach, or launch in Modmii Classic, which interacts like a PC terminal or command promt. Some advanced options may not be accessible in Modmii Skin. A list of the various activities for Modmii Classic can be found below.

2023-08-14 19:34 UTC, playerjmr commented
i think all thats left is to add it to site navigation, correct? im not sure how to do that from my end tho :/

2023-08-19 14:24 UTC, Naim2000 approved these changes

2023-08-20 01:23 UTC, merged