Add Wilbrand Web instructions to the Wilbrand page
RiiConnect24/Wii-Guide pull request #381
Opened 2023-08-12 20:05 UTC by jornmann

Wilbrand Web is a web frontend for Wilbrand that I recently wrote, you can see it at [https://wilbrand.donut.eu.org/](https://wilbrand.donut.eu.org/). This way, it is as easy to use as LetterBomb.
I thought it would be a good idea to add instructions on how to use it to wii.guide.
This is my first contribution to wii.guide, so let me know if I made any mistakes.
Thank you!

2023-08-12 21:13 UTC, Naim2000 commented on _pages/en_US/wilbrand.md
> +1.  Visit [wilbrand.donut.eu.org](https://wilbrand.donut.eu.org/), input your Wii MAC, version, region, ensure `Bundle the HackMii Installer for me!` is checked, and cut either wire.
By the way you have the readme's bundled with the HackMii installer? I'm moving in a minute so I can't check

2023-08-12 21:24 UTC, jornmann commented on _pages/en_US/wilbrand.md
> +1.  Visit [wilbrand.donut.eu.org](https://wilbrand.donut.eu.org/), input your Wii MAC, version, region, ensure `Bundle the HackMii Installer for me!` is checked, and cut either wire.
yes, the readmes and licenses are added along with the installer

2023-08-13 23:12 UTC, Naim2000 requested changes

2023-08-13 23:12 UTC, Naim2000 commented on _pages/en_US/wilbrand.md
> +
```suggestion
Unlike LetterBomb, Wilbrand supports Wii menu versions down to 3.0.
{: .notice--info}

```
Where'd this go

2023-08-13 23:12 UTC, Naim2000 commented on _pages/en_US/wilbrand.md
> +If this didn't work for you, try another exploit or try Wilbrand.
```suggestion
If this didn't work for you, [try another exploit](get-started) or try the normal [Wilbrand](#wilbrand).
```
Hyperlinks are built like that
oh and "or try Wilbrand" sounds kinda silly, like this is Wilbrand in the first place

2023-08-13 23:21 UTC, playerjmr commented on _pages/en_US/wilbrand.md
> +If this didn't work for you, try another exploit or try Wilbrand.
```suggestion
If this didn't work for you, [try another exploit](get-started) or try [Wilbrand CLI](#wilbrand).
```

2023-08-13 23:33 UTC, Naim2000 commented on _pages/en_US/wilbrand.md
> +If this didn't work for you, try another exploit or try Wilbrand.
Fair

2023-08-18 18:01 UTC, Naim2000 approved these changes
Pro tip: use separate branches for your pull requests, I squash a lot

2023-08-18 18:01 UTC, merged